### ISSUE TITLE
Typo in CLI help text 

### ISSUE THREAD

**Issue by ryan-sheldrake** [fossas/spectrometer#168] opened 2020-12-07 12:53 UTC
The short version of --output needs to be "--o" and not as it currently is below. Very minor issue. 

Usage: fossa2 analyze [**-o|**--output] [--unpack-archives] [--branch ARG]
                      [--title ARG] [--project-url ARG] [--jira-project-key ARG]
                      [--link ARG] [--team ARG] [--policy ARG]
                      [--filter ANALYSIS-TARGET] [DIR]
  Scan for projects and their dependencies

**Comment by scruffystuffs** [comment] 2020-12-07 18:33
By convention, short options are only prefixed with single dashes, while long options are prefixed with two dashes.  Based on the help text I'm seeing, we are currently in line with both our intended layout and established conventions.  Have you seen a case where `--o` works as expected?  Please include a recording for evidence if you do see this.

**Comment by scruffystuffs** [comment] 2020-12-07 19:57
I ran a test on the latest version and confirmed that we support `-o`, but not `--o`, which is expected behavior.  I also confirmed that our help text matches the one you provided, at least in terms of the `output` option.

**Comment by ryan-sheldrake** [comment] 2020-12-08 17:11
Great - do you want to remove the "l" after -o in the help text?

**Comment by scruffystuffs** [comment] 2020-12-08 18:27
That's meant to represent "Either `-o` or `--output`".  When options are identical or mutually exclusive, the vertical pipe character is used to communicate that only one of the options in a series of pipes should be used.  Wrapping that sequence in `[square brackets]` tells the user that the options are not required and can be left out entirely.   These are both semi-standard conventions in CLI help texts.

Example:
```
Usage: some-program [--foo|--bar|--baz]
```

This would mean that a user should choose one of `--foo`, `--bar`, `--baz`, or none of them.

**Comment by scruffystuffs** [comment] 2020-12-08 18:29
Since I've confirmed that the help text is working as expected, I'm going to close this issue.  Feel free to reach out to me or @liftM if you have more questions.

**Closed by scruffystuffs** 2020-12-08 18:29 UTC
